INSERT INTO companies (company_user_id, company_name, company_website_url, company_logo, company_type, company_location)
VALUES
    (NULL, 'Google', 'https://www.google.com', 'https://logos.hunter.io/google.com', 'Enterprise', 'Mountain View, CA'),
    (NULL, 'Microsoft', 'https://www.microsoft.com', 'https://logos.hunter.io/microsoft.com', 'Enterprise', 'Redmond, WA'),
    (NULL, 'Amazon', 'https://www.amazon.com', 'https://logos.hunter.io/amazon.com', 'Enterprise', 'Seattle, WA'),
    (NULL, 'Apple', 'https://www.apple.com', 'https://logos.hunter.io/apple.com', 'Enterprise', 'Cupertino, CA'),
    (NULL, 'Meta', 'https://www.meta.com', 'https://logos.hunter.io/meta.com', 'Enterprise', 'Menlo Park, CA'),
    (NULL, 'NVIDIA', 'https://www.nvidia.com', 'https://logos.hunter.io/nvidia.com', 'Enterprise', 'Santa Clara, CA'),
    (NULL, 'Netflix', 'https://www.netflix.com', 'https://logos.hunter.io/netflix.com', 'Enterprise', 'Los Gatos, CA'),
    (NULL, 'Tesla', 'https://www.tesla.com', 'https://logos.hunter.io/tesla.com', 'Enterprise', 'Austin, TX'),
    (NULL, 'Adobe', 'https://www.adobe.com', 'https://logos.hunter.io/adobe.com', 'Enterprise', 'San Jose, CA'),
    (NULL, 'Salesforce', 'https://www.salesforce.com', 'https://logos.hunter.io/salesforce.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'Oracle', 'https://www.oracle.com', 'https://logos.hunter.io/oracle.com', 'Enterprise', 'Austin, TX'),
    (NULL, 'IBM', 'https://www.ibm.com', 'https://logos.hunter.io/ibm.com', 'Enterprise', 'Armonk, NY'),
    (NULL, 'Intel', 'https://www.intel.com', 'https://logos.hunter.io/intel.com', 'Enterprise', 'Santa Clara, CA'),
    (NULL, 'Cisco', 'https://www.cisco.com', 'https://logos.hunter.io/cisco.com', 'Enterprise', 'San Jose, CA'),
    (NULL, 'SAP', 'https://www.sap.com', 'https://logos.hunter.io/sap.com', 'Enterprise', 'Walldorf, Germany'),
    (NULL, 'ServiceNow', 'https://www.servicenow.com', 'https://logos.hunter.io/servicenow.com', 'Enterprise', 'Santa Clara, CA'),
    (NULL, 'Workday', 'https://www.workday.com', 'https://logos.hunter.io/workday.com', 'Enterprise', 'Pleasanton, CA'),
    (NULL, 'Snowflake', 'https://www.snowflake.com', 'https://logos.hunter.io/snowflake.com', 'Enterprise', 'Bozeman, MT'),
    (NULL, 'Palantir', 'https://www.palantir.com', 'https://logos.hunter.io/palantir.com', 'Enterprise', 'Denver, CO'),
    (NULL, 'Uber', 'https://www.uber.com', 'https://logos.hunter.io/uber.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'Airbnb', 'https://www.airbnb.com', 'https://logos.hunter.io/airbnb.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'Lyft', 'https://www.lyft.com', 'https://logos.hunter.io/lyft.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'DoorDash', 'https://www.doordash.com', 'https://logos.hunter.io/doordash.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'Stripe', 'https://www.stripe.com', 'https://logos.hunter.io/stripe.com', 'Fintech', 'San Francisco, CA'),
    (NULL, 'PayPal', 'https://www.paypal.com', 'https://logos.hunter.io/paypal.com', 'Fintech', 'San Jose, CA'),
    (NULL, 'Square', 'https://www.squareup.com', 'https://logos.hunter.io/squareup.com', 'Fintech', 'Oakland, CA'),
    (NULL, 'Block', 'https://www.block.xyz', 'https://logos.hunter.io/block.xyz', 'Fintech', 'Oakland, CA'),
    (NULL, 'Coinbase', 'https://www.coinbase.com', 'https://logos.hunter.io/coinbase.com', 'Fintech', 'Remote, US'),
    (NULL, 'Robinhood', 'https://www.robinhood.com', 'https://logos.hunter.io/robinhood.com', 'Fintech', 'Menlo Park, CA'),
    (NULL, 'Plaid', 'https://www.plaid.com', 'https://logos.hunter.io/plaid.com', 'Fintech', 'San Francisco, CA'),
    (NULL, 'Adyen', 'https://www.adyen.com', 'https://logos.hunter.io/adyen.com', 'Fintech', 'Amsterdam, Netherlands'),
    (NULL, 'Revolut', 'https://www.revolut.com', 'https://logos.hunter.io/revolut.com', 'Fintech', 'London, UK'),
    (NULL, 'Klarna', 'https://www.klarna.com', 'https://logos.hunter.io/klarna.com', 'Fintech', 'Stockholm, Sweden'),
    (NULL, 'Wise', 'https://www.wise.com', 'https://logos.hunter.io/wise.com', 'Fintech', 'London, UK'),
    (NULL, 'N26', 'https://www.n26.com', 'https://logos.hunter.io/n26.com', 'Fintech', 'Berlin, Germany'),
    (NULL, 'Monzo', 'https://www.monzo.com', 'https://logos.hunter.io/monzo.com', 'Fintech', 'London, UK'),
    (NULL, 'Chime', 'https://www.chime.com', 'https://logos.hunter.io/chime.com', 'Fintech', 'San Francisco, CA'),
    (NULL, 'Brex', 'https://www.brex.com', 'https://logos.hunter.io/brex.com', 'Fintech', 'San Francisco, CA'),
    (NULL, 'Ramp', 'https://www.ramp.com', 'https://logos.hunter.io/ramp.com', 'Fintech', 'New York, NY'),
    (NULL, 'Affirm', 'https://www.affirm.com', 'https://logos.hunter.io/affirm.com', 'Fintech', 'San Francisco, CA'),
    (NULL, 'SoFi', 'https://www.sofi.com', 'https://logos.hunter.io/sofi.com', 'Fintech', 'San Francisco, CA'),
    (NULL, 'GitHub', 'https://www.github.com', 'https://logos.hunter.io/github.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'GitLab', 'https://www.gitlab.com', 'https://logos.hunter.io/gitlab.com', 'Developer Tools', 'Remote, US'),
    (NULL, 'Atlassian', 'https://www.atlassian.com', 'https://logos.hunter.io/atlassian.com', 'Developer Tools', 'Sydney, Australia'),
    (NULL, 'JetBrains', 'https://www.jetbrains.com', 'https://logos.hunter.io/jetbrains.com', 'Developer Tools', 'Prague, Czech Republic'),
    (NULL, 'Docker', 'https://www.docker.com', 'https://logos.hunter.io/docker.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'HashiCorp', 'https://www.hashicorp.com', 'https://logos.hunter.io/hashicorp.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Datadog', 'https://www.datadoghq.com', 'https://logos.hunter.io/datadoghq.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'New Relic', 'https://www.newrelic.com', 'https://logos.hunter.io/newrelic.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Splunk', 'https://www.splunk.com', 'https://logos.hunter.io/splunk.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Elastic', 'https://www.elastic.co', 'https://logos.hunter.io/elastic.co', 'Developer Tools', 'Mountain View, CA'),
    (NULL, 'MongoDB', 'https://www.mongodb.com', 'https://logos.hunter.io/mongodb.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'Redis', 'https://www.redis.io', 'https://logos.hunter.io/redis.io', 'Developer Tools', 'Mountain View, CA'),
    (NULL, 'Confluent', 'https://www.confluent.io', 'https://logos.hunter.io/confluent.io', 'Developer Tools', 'Mountain View, CA'),
    (NULL, 'Databricks', 'https://www.databricks.com', 'https://logos.hunter.io/databricks.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Snowplow', 'https://www.snowplow.io', 'https://logos.hunter.io/snowplow.io', 'Developer Tools', 'London, UK'),
    (NULL, 'Grafana Labs', 'https://www.grafana.com', 'https://logos.hunter.io/grafana.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'PagerDuty', 'https://www.pagerduty.com', 'https://logos.hunter.io/pagerduty.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'LaunchDarkly', 'https://www.launchdarkly.com', 'https://logos.hunter.io/launchdarkly.com', 'Developer Tools', 'Oakland, CA'),
    (NULL, 'CircleCI', 'https://www.circleci.com', 'https://logos.hunter.io/circleci.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Travis CI', 'https://www.travis-ci.com', 'https://logos.hunter.io/travis-ci.com', 'Developer Tools', 'Berlin, Germany'),
    (NULL, 'JFrog', 'https://www.jfrog.com', 'https://logos.hunter.io/jfrog.com', 'Developer Tools', 'Sunnyvale, CA'),
    (NULL, 'Sonatype', 'https://www.sonatype.com', 'https://logos.hunter.io/sonatype.com', 'Developer Tools', 'Fulton, MD'),
    (NULL, 'Snyk', 'https://www.snyk.io', 'https://logos.hunter.io/snyk.io', 'Developer Tools', 'Boston, MA'),
    (NULL, 'Postman', 'https://www.postman.com', 'https://logos.hunter.io/postman.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Twilio', 'https://www.twilio.com', 'https://logos.hunter.io/twilio.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Auth0', 'https://www.auth0.com', 'https://logos.hunter.io/auth0.com', 'Developer Tools', 'Bellevue, WA'),
    (NULL, 'Okta', 'https://www.okta.com', 'https://logos.hunter.io/okta.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Cloudflare', 'https://www.cloudflare.com', 'https://logos.hunter.io/cloudflare.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Fastly', 'https://www.fastly.com', 'https://logos.hunter.io/fastly.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Akamai', 'https://www.akamai.com', 'https://logos.hunter.io/akamai.com', 'Developer Tools', 'Cambridge, MA'),
    (NULL, 'Vercel', 'https://www.vercel.com', 'https://logos.hunter.io/vercel.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Netlify', 'https://www.netlify.com', 'https://logos.hunter.io/netlify.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Render', 'https://www.render.com', 'https://logos.hunter.io/render.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Fly.io', 'https://www.fly.io', 'https://logos.hunter.io/fly.io', 'Developer Tools', 'Chicago, IL'),
    (NULL, 'DigitalOcean', 'https://www.digitalocean.com', 'https://logos.hunter.io/digitalocean.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'Linode', 'https://www.linode.com', 'https://logos.hunter.io/linode.com', 'Developer Tools', 'Philadelphia, PA'),
    (NULL, 'Hetzner', 'https://www.hetzner.com', 'https://logos.hunter.io/hetzner.com', 'Developer Tools', 'Gunzenhausen, Germany'),
    (NULL, 'OVHcloud', 'https://www.ovhcloud.com', 'https://logos.hunter.io/ovhcloud.com', 'Developer Tools', 'Roubaix, France'),
    (NULL, 'OpenAI', 'https://www.openai.com', 'https://logos.hunter.io/openai.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Anthropic', 'https://www.anthropic.com', 'https://logos.hunter.io/anthropic.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Hugging Face', 'https://www.huggingface.co', 'https://logos.hunter.io/huggingface.co', 'AI/ML', 'New York, NY'),
    (NULL, 'Cohere', 'https://www.cohere.com', 'https://logos.hunter.io/cohere.com', 'AI/ML', 'Toronto, Canada'),
    (NULL, 'Mistral AI', 'https://www.mistral.ai', 'https://logos.hunter.io/mistral.ai', 'AI/ML', 'Paris, France'),
    (NULL, 'Stability AI', 'https://www.stability.ai', 'https://logos.hunter.io/stability.ai', 'AI/ML', 'London, UK'),
    (NULL, 'Scale AI', 'https://www.scale.com', 'https://logos.hunter.io/scale.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Weights & Biases', 'https://www.wandb.ai', 'https://logos.hunter.io/wandb.ai', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'DeepMind', 'https://www.deepmind.com', 'https://logos.hunter.io/deepmind.com', 'AI/ML', 'London, UK'),
    (NULL, 'C3.ai', 'https://www.c3.ai', 'https://logos.hunter.io/c3.ai', 'AI/ML', 'Redwood City, CA'),
    (NULL, 'UiPath', 'https://www.uipath.com', 'https://logos.hunter.io/uipath.com', 'AI/ML', 'New York, NY'),
    (NULL, 'DataRobot', 'https://www.datarobot.com', 'https://logos.hunter.io/datarobot.com', 'AI/ML', 'Boston, MA'),
    (NULL, 'HubSpot', 'https://www.hubspot.com', 'https://logos.hunter.io/hubspot.com', 'SaaS', 'Cambridge, MA'),
    (NULL, 'Zendesk', 'https://www.zendesk.com', 'https://logos.hunter.io/zendesk.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Freshworks', 'https://www.freshworks.com', 'https://logos.hunter.io/freshworks.com', 'SaaS', 'San Mateo, CA'),
    (NULL, 'Intercom', 'https://www.intercom.com', 'https://logos.hunter.io/intercom.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Drift', 'https://www.drift.com', 'https://logos.hunter.io/drift.com', 'SaaS', 'Boston, MA'),
    (NULL, 'Gong', 'https://www.gong.io', 'https://logos.hunter.io/gong.io', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Outreach', 'https://www.outreach.io', 'https://logos.hunter.io/outreach.io', 'SaaS', 'Seattle, WA'),
    (NULL, 'Salesloft', 'https://www.salesloft.com', 'https://logos.hunter.io/salesloft.com', 'SaaS', 'Atlanta, GA'),
    (NULL, 'Clari', 'https://www.clari.com', 'https://logos.hunter.io/clari.com', 'SaaS', 'Sunnyvale, CA'),
    (NULL, 'Airtable', 'https://www.airtable.com', 'https://logos.hunter.io/airtable.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Notion', 'https://www.notion.so', 'https://logos.hunter.io/notion.so', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Asana', 'https://www.asana.com', 'https://logos.hunter.io/asana.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Monday.com', 'https://www.monday.com', 'https://logos.hunter.io/monday.com', 'SaaS', 'Tel Aviv, Israel'),
    (NULL, 'ClickUp', 'https://www.clickup.com', 'https://logos.hunter.io/clickup.com', 'SaaS', 'San Diego, CA'),
    (NULL, 'Smartsheet', 'https://www.smartsheet.com', 'https://logos.hunter.io/smartsheet.com', 'SaaS', 'Bellevue, WA'),
    (NULL, 'Miro', 'https://www.miro.com', 'https://logos.hunter.io/miro.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Figma', 'https://www.figma.com', 'https://logos.hunter.io/figma.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Canva', 'https://www.canva.com', 'https://logos.hunter.io/canva.com', 'SaaS', 'Sydney, Australia'),
    (NULL, 'Adobe Experience Cloud', 'https://www.business.adobe.com', 'https://logos.hunter.io/business.adobe.com', 'SaaS', 'San Jose, CA'),
    (NULL, 'Box', 'https://www.box.com', 'https://logos.hunter.io/box.com', 'SaaS', 'Redwood City, CA'),
    (NULL, 'Dropbox', 'https://www.dropbox.com', 'https://logos.hunter.io/dropbox.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Slack', 'https://www.slack.com', 'https://logos.hunter.io/slack.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Zoom', 'https://www.zoom.us', 'https://logos.hunter.io/zoom.us', 'SaaS', 'San Jose, CA'),
    (NULL, 'DocuSign', 'https://www.docusign.com', 'https://logos.hunter.io/docusign.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Twilio Segment', 'https://www.segment.com', 'https://logos.hunter.io/segment.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Amplitude', 'https://www.amplitude.com', 'https://logos.hunter.io/amplitude.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Mixpanel', 'https://www.mixpanel.com', 'https://logos.hunter.io/mixpanel.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Heap', 'https://www.heap.io', 'https://logos.hunter.io/heap.io', 'SaaS', 'San Francisco, CA'),
    (NULL, 'FullStory', 'https://www.fullstory.com', 'https://logos.hunter.io/fullstory.com', 'SaaS', 'Atlanta, GA'),
    (NULL, 'Hotjar', 'https://www.hotjar.com', 'https://logos.hunter.io/hotjar.com', 'SaaS', 'Valletta, Malta'),
    (NULL, 'Shopify', 'https://www.shopify.com', 'https://logos.hunter.io/shopify.com', 'SaaS', 'Ottawa, Canada'),
    (NULL, 'BigCommerce', 'https://www.bigcommerce.com', 'https://logos.hunter.io/bigcommerce.com', 'SaaS', 'Austin, TX'),
    (NULL, 'WooCommerce', 'https://www.woocommerce.com', 'https://logos.hunter.io/woocommerce.com', 'SaaS', 'Remote, US'),
    (NULL, 'Magento', 'https://www.magento.com', 'https://logos.hunter.io/magento.com', 'SaaS', 'Culver City, CA'),
    (NULL, 'Spotify', 'https://www.spotify.com', 'https://logos.hunter.io/spotify.com', 'Consumer Tech', 'Stockholm, Sweden'),
    (NULL, 'Snap', 'https://www.snap.com', 'https://logos.hunter.io/snap.com', 'Consumer Tech', 'Santa Monica, CA'),
    (NULL, 'Pinterest', 'https://www.pinterest.com', 'https://logos.hunter.io/pinterest.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Reddit', 'https://www.reddit.com', 'https://logos.hunter.io/reddit.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Discord', 'https://www.discord.com', 'https://logos.hunter.io/discord.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Twitch', 'https://www.twitch.tv', 'https://logos.hunter.io/twitch.tv', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Roblox', 'https://www.roblox.com', 'https://logos.hunter.io/roblox.com', 'Gaming', 'San Mateo, CA'),
    (NULL, 'Epic Games', 'https://www.epicgames.com', 'https://logos.hunter.io/epicgames.com', 'Gaming', 'Cary, NC'),
    (NULL, 'Riot Games', 'https://www.riotgames.com', 'https://logos.hunter.io/riotgames.com', 'Gaming', 'Los Angeles, CA'),
    (NULL, 'Valve', 'https://www.valvesoftware.com', 'https://logos.hunter.io/valvesoftware.com', 'Gaming', 'Bellevue, WA'),
    (NULL, 'Unity', 'https://www.unity.com', 'https://logos.hunter.io/unity.com', 'Gaming', 'San Francisco, CA'),
    (NULL, 'Electronic Arts', 'https://www.ea.com', 'https://logos.hunter.io/ea.com', 'Gaming', 'Redwood City, CA'),
    (NULL, 'Activision Blizzard', 'https://www.activisionblizzard.com', 'https://logos.hunter.io/activisionblizzard.com', 'Gaming', 'Santa Monica, CA'),
    (NULL, 'Take-Two Interactive', 'https://www.take2games.com', 'https://logos.hunter.io/take2games.com', 'Gaming', 'New York, NY'),
    (NULL, 'Ubisoft', 'https://www.ubisoft.com', 'https://logos.hunter.io/ubisoft.com', 'Gaming', 'Montreuil, France'),
    (NULL, 'CD Projekt', 'https://www.cdprojekt.com', 'https://logos.hunter.io/cdprojekt.com', 'Gaming', 'Warsaw, Poland'),
    (NULL, 'Supercell', 'https://www.supercell.com', 'https://logos.hunter.io/supercell.com', 'Gaming', 'Helsinki, Finland'),
    (NULL, 'King', 'https://www.king.com', 'https://logos.hunter.io/king.com', 'Gaming', 'Stockholm, Sweden'),
    (NULL, 'Zynga', 'https://www.zynga.com', 'https://logos.hunter.io/zynga.com', 'Gaming', 'San Francisco, CA'),
    (NULL, 'LinkedIn', 'https://www.linkedin.com', 'https://logos.hunter.io/linkedin.com', 'Enterprise', 'Sunnyvale, CA'),
    (NULL, 'Twitter', 'https://www.x.com', 'https://logos.hunter.io/x.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'TikTok', 'https://www.tiktok.com', 'https://logos.hunter.io/tiktok.com', 'Consumer Tech', 'Los Angeles, CA'),
    (NULL, 'ByteDance', 'https://www.bytedance.com', 'https://logos.hunter.io/bytedance.com', 'Enterprise', 'Beijing, China'),
    (NULL, 'Baidu', 'https://www.baidu.com', 'https://logos.hunter.io/baidu.com', 'Enterprise', 'Beijing, China'),
    (NULL, 'Alibaba', 'https://www.alibaba.com', 'https://logos.hunter.io/alibaba.com', 'Enterprise', 'Hangzhou, China'),
    (NULL, 'Tencent', 'https://www.tencent.com', 'https://logos.hunter.io/tencent.com', 'Enterprise', 'Shenzhen, China'),
    (NULL, 'Samsung', 'https://www.samsung.com', 'https://logos.hunter.io/samsung.com', 'Enterprise', 'Suwon, South Korea'),
    (NULL, 'Sony', 'https://www.sony.com', 'https://logos.hunter.io/sony.com', 'Enterprise', 'Tokyo, Japan'),
    (NULL, 'LG', 'https://www.lg.com', 'https://logos.hunter.io/lg.com', 'Enterprise', 'Seoul, South Korea'),
    (NULL, 'ASML', 'https://www.asml.com', 'https://logos.hunter.io/asml.com', 'Enterprise', 'Veldhoven, Netherlands'),
    (NULL, 'TSMC', 'https://www.tsmc.com', 'https://logos.hunter.io/tsmc.com', 'Enterprise', 'Hsinchu, Taiwan'),
    (NULL, 'Broadcom', 'https://www.broadcom.com', 'https://logos.hunter.io/broadcom.com', 'Enterprise', 'Palo Alto, CA'),
    (NULL, 'Qualcomm', 'https://www.qualcomm.com', 'https://logos.hunter.io/qualcomm.com', 'Enterprise', 'San Diego, CA'),
    (NULL, 'AMD', 'https://www.amd.com', 'https://logos.hunter.io/amd.com', 'Enterprise', 'Santa Clara, CA'),
    (NULL, 'Micron', 'https://www.micron.com', 'https://logos.hunter.io/micron.com', 'Enterprise', 'Boise, ID'),
    (NULL, 'Applied Materials', 'https://www.appliedmaterials.com', 'https://logos.hunter.io/appliedmaterials.com', 'Enterprise', 'Santa Clara, CA'),
    (NULL, 'Lam Research', 'https://www.lamresearch.com', 'https://logos.hunter.io/lamresearch.com', 'Enterprise', 'Fremont, CA'),
    (NULL, 'KLA', 'https://www.kla.com', 'https://logos.hunter.io/kla.com', 'Enterprise', 'Milpitas, CA'),
    (NULL, 'Arm', 'https://www.arm.com', 'https://logos.hunter.io/arm.com', 'Enterprise', 'Cambridge, UK'),
    (NULL, 'MediaTek', 'https://www.mediatek.com', 'https://logos.hunter.io/mediatek.com', 'Enterprise', 'Hsinchu, Taiwan'),
    (NULL, 'Dell Technologies', 'https://www.dell.com', 'https://logos.hunter.io/dell.com', 'Enterprise', 'Round Rock, TX'),
    (NULL, 'HP', 'https://www.hp.com', 'https://logos.hunter.io/hp.com', 'Enterprise', 'Palo Alto, CA'),
    (NULL, 'HPE', 'https://www.hpe.com', 'https://logos.hunter.io/hpe.com', 'Enterprise', 'Houston, TX'),
    (NULL, 'Lenovo', 'https://www.lenovo.com', 'https://logos.hunter.io/lenovo.com', 'Enterprise', 'Morrisville, NC'),
    (NULL, 'VMware', 'https://www.vmware.com', 'https://logos.hunter.io/vmware.com', 'Enterprise', 'Palo Alto, CA'),
    (NULL, 'Red Hat', 'https://www.redhat.com', 'https://logos.hunter.io/redhat.com', 'Enterprise', 'Raleigh, NC'),
    (NULL, 'Canonical', 'https://www.canonical.com', 'https://logos.hunter.io/canonical.com', 'Enterprise', 'London, UK'),
    (NULL, 'SUSE', 'https://www.suse.com', 'https://logos.hunter.io/suse.com', 'Enterprise', 'Nuremberg, Germany'),
    (NULL, 'CrowdStrike', 'https://www.crowdstrike.com', 'https://logos.hunter.io/crowdstrike.com', 'Enterprise', 'Austin, TX'),
    (NULL, 'Palo Alto Networks', 'https://www.paloaltonetworks.com', 'https://logos.hunter.io/paloaltonetworks.com', 'Enterprise', 'Santa Clara, CA'),
    (NULL, 'Fortinet', 'https://www.fortinet.com', 'https://logos.hunter.io/fortinet.com', 'Enterprise', 'Sunnyvale, CA'),
    (NULL, 'Zscaler', 'https://www.zscaler.com', 'https://logos.hunter.io/zscaler.com', 'Enterprise', 'San Jose, CA'),
    (NULL, 'SentinelOne', 'https://www.sentinelone.com', 'https://logos.hunter.io/sentinelone.com', 'Enterprise', 'Mountain View, CA'),
    (NULL, 'Rapid7', 'https://www.rapid7.com', 'https://logos.hunter.io/rapid7.com', 'Enterprise', 'Boston, MA'),
    (NULL, 'Tenable', 'https://www.tenable.com', 'https://logos.hunter.io/tenable.com', 'Enterprise', 'Columbia, MD'),
    (NULL, 'Proofpoint', 'https://www.proofpoint.com', 'https://logos.hunter.io/proofpoint.com', 'Enterprise', 'Sunnyvale, CA'),
    (NULL, 'Mimecast', 'https://www.mimecast.com', 'https://logos.hunter.io/mimecast.com', 'Enterprise', 'Lexington, MA'),
    (NULL, '1Password', 'https://www.1password.com', 'https://logos.hunter.io/1password.com', 'Enterprise', 'Toronto, Canada'),
    (NULL, 'LastPass', 'https://www.lastpass.com', 'https://logos.hunter.io/lastpass.com', 'Enterprise', 'Boston, MA'),
    (NULL, 'Bitwarden', 'https://www.bitwarden.com', 'https://logos.hunter.io/bitwarden.com', 'Enterprise', 'Santa Barbara, CA'),
    (NULL, 'Nord Security', 'https://www.nordsecurity.com', 'https://logos.hunter.io/nordsecurity.com', 'Enterprise', 'Vilnius, Lithuania'),
    (NULL, 'Mercado Libre', 'https://www.mercadolibre.com', 'https://logos.hunter.io/mercadolibre.com', 'Enterprise', 'Montevideo, Uruguay'),
    (NULL, 'Nubank', 'https://www.nubank.com.br', 'https://logos.hunter.io/nubank.com.br', 'Fintech', 'Sao Paulo, Brazil'),
    (NULL, 'Grab', 'https://www.grab.com', 'https://logos.hunter.io/grab.com', 'Enterprise', 'Singapore'),
    (NULL, 'Gojek', 'https://www.gojek.com', 'https://logos.hunter.io/gojek.com', 'Enterprise', 'Jakarta, Indonesia'),
    (NULL, 'Sea Limited', 'https://www.sea.com', 'https://logos.hunter.io/sea.com', 'Enterprise', 'Singapore'),
    (NULL, 'Rakuten', 'https://www.rakuten.com', 'https://logos.hunter.io/rakuten.com', 'Enterprise', 'Tokyo, Japan'),
    (NULL, 'Flipkart', 'https://www.flipkart.com', 'https://logos.hunter.io/flipkart.com', 'Enterprise', 'Bengaluru, India'),
    (NULL, 'Infosys', 'https://www.infosys.com', 'https://logos.hunter.io/infosys.com', 'Enterprise', 'Bengaluru, India'),
    (NULL, 'TCS', 'https://www.tcs.com', 'https://logos.hunter.io/tcs.com', 'Enterprise', 'Mumbai, India'),
    (NULL, 'Wipro', 'https://www.wipro.com', 'https://logos.hunter.io/wipro.com', 'Enterprise', 'Bengaluru, India'),
    (NULL, 'HCLTech', 'https://www.hcltech.com', 'https://logos.hunter.io/hcltech.com', 'Enterprise', 'Noida, India'),
    (NULL, 'Capgemini', 'https://www.capgemini.com', 'https://logos.hunter.io/capgemini.com', 'Enterprise', 'Paris, France'),
    (NULL, 'Accenture', 'https://www.accenture.com', 'https://logos.hunter.io/accenture.com', 'Enterprise', 'Dublin, Ireland'),
    (NULL, 'Deloitte Digital', 'https://www.deloitte.com', 'https://logos.hunter.io/deloitte.com', 'Enterprise', 'London, UK'),
    (NULL, 'EPAM', 'https://www.epam.com', 'https://logos.hunter.io/epam.com', 'Enterprise', 'Newtown, PA'),
    (NULL, 'Globant', 'https://www.globant.com', 'https://logos.hunter.io/globant.com', 'Enterprise', 'Luxembourg City, Luxembourg'),
    (NULL, 'Thoughtworks', 'https://www.thoughtworks.com', 'https://logos.hunter.io/thoughtworks.com', 'Enterprise', 'Chicago, IL'),
    (NULL, 'Cognizant', 'https://www.cognizant.com', 'https://logos.hunter.io/cognizant.com', 'Enterprise', 'Teaneck, NJ'),
    (NULL, 'Infosys Finacle', 'https://www.finacle.com', 'https://logos.hunter.io/finacle.com', 'Fintech', 'Bengaluru, India'),
    (NULL, 'Booking.com', 'https://www.booking.com', 'https://logos.hunter.io/booking.com', 'Consumer Tech', 'Amsterdam, Netherlands'),
    (NULL, 'Expedia', 'https://www.expedia.com', 'https://logos.hunter.io/expedia.com', 'Consumer Tech', 'Seattle, WA'),
    (NULL, 'Tripadvisor', 'https://www.tripadvisor.com', 'https://logos.hunter.io/tripadvisor.com', 'Consumer Tech', 'Needham, MA'),
    (NULL, 'eBay', 'https://www.ebay.com', 'https://logos.hunter.io/ebay.com', 'Consumer Tech', 'San Jose, CA'),
    (NULL, 'Etsy', 'https://www.etsy.com', 'https://logos.hunter.io/etsy.com', 'Consumer Tech', 'Brooklyn, NY'),
    (NULL, 'Wayfair', 'https://www.wayfair.com', 'https://logos.hunter.io/wayfair.com', 'Consumer Tech', 'Boston, MA'),
    (NULL, 'Chewy', 'https://www.chewy.com', 'https://logos.hunter.io/chewy.com', 'Consumer Tech', 'Dania Beach, FL'),
    (NULL, 'Instacart', 'https://www.instacart.com', 'https://logos.hunter.io/instacart.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Deliveroo', 'https://www.deliveroo.co.uk', 'https://logos.hunter.io/deliveroo.co.uk', 'Consumer Tech', 'London, UK'),
    (NULL, 'Just Eat Takeaway', 'https://www.justeattakeaway.com', 'https://logos.hunter.io/justeattakeaway.com', 'Consumer Tech', 'Amsterdam, Netherlands'),
    (NULL, 'Zalando', 'https://www.zalando.com', 'https://logos.hunter.io/zalando.com', 'Consumer Tech', 'Berlin, Germany'),
    (NULL, 'ASOS', 'https://www.asos.com', 'https://logos.hunter.io/asos.com', 'Consumer Tech', 'London, UK'),
    (NULL, 'Farfetch', 'https://www.farfetch.com', 'https://logos.hunter.io/farfetch.com', 'Consumer Tech', 'London, UK'),
    (NULL, 'Rakuten Viber', 'https://www.viber.com', 'https://logos.hunter.io/viber.com', 'Consumer Tech', 'Luxembourg City, Luxembourg'),
    (NULL, 'WiseTech Global', 'https://www.wisetechglobal.com', 'https://logos.hunter.io/wisetechglobal.com', 'SaaS', 'Sydney, Australia'),
    (NULL, 'Atlassian Jira', 'https://www.jira.com', 'https://logos.hunter.io/jira.com', 'SaaS', 'Sydney, Australia'),
    (NULL, 'Linear', 'https://www.linear.app', 'https://logos.hunter.io/linear.app', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Height', 'https://www.height.app', 'https://logos.hunter.io/height.app', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Shortcut', 'https://www.shortcut.com', 'https://logos.hunter.io/shortcut.com', 'SaaS', 'New York, NY'),
    (NULL, 'Jira Align', 'https://www.jiraalign.com', 'https://logos.hunter.io/jiraalign.com', 'SaaS', 'Sydney, Australia'),
    (NULL, 'Basecamp', 'https://www.basecamp.com', 'https://logos.hunter.io/basecamp.com', 'SaaS', 'Chicago, IL'),
    (NULL, 'Trello', 'https://www.trello.com', 'https://logos.hunter.io/trello.com', 'SaaS', 'New York, NY'),
    (NULL, 'Coda', 'https://www.coda.io', 'https://logos.hunter.io/coda.io', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Aha!', 'https://www.aha.io', 'https://logos.hunter.io/aha.io', 'SaaS', 'Menlo Park, CA'),
    (NULL, 'Productboard', 'https://www.productboard.com', 'https://logos.hunter.io/productboard.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Pendo', 'https://www.pendo.io', 'https://logos.hunter.io/pendo.io', 'SaaS', 'Raleigh, NC'),
    (NULL, 'Gainsight', 'https://www.gainsight.com', 'https://logos.hunter.io/gainsight.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Totango', 'https://www.totango.com', 'https://logos.hunter.io/totango.com', 'SaaS', 'Redwood City, CA'),
    (NULL, 'ChurnZero', 'https://www.churnzero.com', 'https://logos.hunter.io/churnzero.com', 'SaaS', 'Washington, DC'),
    (NULL, 'Braze', 'https://www.braze.com', 'https://logos.hunter.io/braze.com', 'SaaS', 'New York, NY'),
    (NULL, 'Iterable', 'https://www.iterable.com', 'https://logos.hunter.io/iterable.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Customer.io', 'https://www.customer.io', 'https://logos.hunter.io/customer.io', 'SaaS', 'Portland, OR'),
    (NULL, 'Klaviyo', 'https://www.klaviyo.com', 'https://logos.hunter.io/klaviyo.com', 'SaaS', 'Boston, MA'),
    (NULL, 'Mailchimp', 'https://www.mailchimp.com', 'https://logos.hunter.io/mailchimp.com', 'SaaS', 'Atlanta, GA'),
    (NULL, 'SendGrid', 'https://www.sendgrid.com', 'https://logos.hunter.io/sendgrid.com', 'SaaS', 'Denver, CO'),
    (NULL, 'Mailgun', 'https://www.mailgun.com', 'https://logos.hunter.io/mailgun.com', 'SaaS', 'San Antonio, TX'),
    (NULL, 'Postmark', 'https://www.postmarkapp.com', 'https://logos.hunter.io/postmarkapp.com', 'SaaS', 'Philadelphia, PA'),
    (NULL, 'Resend', 'https://www.resend.com', 'https://logos.hunter.io/resend.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Supabase', 'https://www.supabase.com', 'https://logos.hunter.io/supabase.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'PlanetScale', 'https://www.planetscale.com', 'https://logos.hunter.io/planetscale.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Neon', 'https://www.neon.tech', 'https://logos.hunter.io/neon.tech', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Cockroach Labs', 'https://www.cockroachlabs.com', 'https://logos.hunter.io/cockroachlabs.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'Timescale', 'https://www.timescale.com', 'https://logos.hunter.io/timescale.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'SingleStore', 'https://www.singlestore.com', 'https://logos.hunter.io/singlestore.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'QuestDB', 'https://www.questdb.io', 'https://logos.hunter.io/questdb.io', 'Developer Tools', 'London, UK'),
    (NULL, 'ClickHouse', 'https://www.clickhouse.com', 'https://logos.hunter.io/clickhouse.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'DuckDB', 'https://www.duckdb.org', 'https://logos.hunter.io/duckdb.org', 'Developer Tools', 'Amsterdam, Netherlands'),
    (NULL, 'Pinecone', 'https://www.pinecone.io', 'https://logos.hunter.io/pinecone.io', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Weaviate', 'https://www.weaviate.io', 'https://logos.hunter.io/weaviate.io', 'AI/ML', 'Amsterdam, Netherlands'),
    (NULL, 'Qdrant', 'https://www.qdrant.tech', 'https://logos.hunter.io/qdrant.tech', 'AI/ML', 'Berlin, Germany'),
    (NULL, 'Chroma', 'https://www.trychroma.com', 'https://logos.hunter.io/trychroma.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'LangChain', 'https://www.langchain.com', 'https://logos.hunter.io/langchain.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'LlamaIndex', 'https://www.llamaindex.ai', 'https://logos.hunter.io/llamaindex.ai', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Replicate', 'https://www.replicate.com', 'https://logos.hunter.io/replicate.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Runway', 'https://www.runwayml.com', 'https://logos.hunter.io/runwayml.com', 'AI/ML', 'New York, NY'),
    (NULL, 'Midjourney', 'https://www.midjourney.com', 'https://logos.hunter.io/midjourney.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Character.AI', 'https://www.character.ai', 'https://logos.hunter.io/character.ai', 'AI/ML', 'Menlo Park, CA'),
    (NULL, 'Perplexity', 'https://www.perplexity.ai', 'https://logos.hunter.io/perplexity.ai', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Jasper', 'https://www.jasper.ai', 'https://logos.hunter.io/jasper.ai', 'AI/ML', 'Austin, TX'),
    (NULL, 'Copy.ai', 'https://www.copy.ai', 'https://logos.hunter.io/copy.ai', 'AI/ML', 'Remote, US'),
    (NULL, 'Grammarly', 'https://www.grammarly.com', 'https://logos.hunter.io/grammarly.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Duolingo', 'https://www.duolingo.com', 'https://logos.hunter.io/duolingo.com', 'Consumer Tech', 'Pittsburgh, PA'),
    (NULL, 'Coursera', 'https://www.coursera.org', 'https://logos.hunter.io/coursera.org', 'Consumer Tech', 'Mountain View, CA'),
    (NULL, 'Udemy', 'https://www.udemy.com', 'https://logos.hunter.io/udemy.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Khan Academy', 'https://www.khanacademy.org', 'https://logos.hunter.io/khanacademy.org', 'Consumer Tech', 'Mountain View, CA'),
    (NULL, 'Pluralsight', 'https://www.pluralsight.com', 'https://logos.hunter.io/pluralsight.com', 'Consumer Tech', 'Draper, UT'),
    (NULL, 'Codecademy', 'https://www.codecademy.com', 'https://logos.hunter.io/codecademy.com', 'Consumer Tech', 'New York, NY'),
    (NULL, 'Gitpod', 'https://www.gitpod.io', 'https://logos.hunter.io/gitpod.io', 'Developer Tools', 'Kiel, Germany'),
    (NULL, 'Replit', 'https://www.replit.com', 'https://logos.hunter.io/replit.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'CodeSandbox', 'https://www.codesandbox.io', 'https://logos.hunter.io/codesandbox.io', 'Developer Tools', 'Amsterdam, Netherlands'),
    (NULL, 'StackBlitz', 'https://www.stackblitz.com', 'https://logos.hunter.io/stackblitz.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Sourcegraph', 'https://www.sourcegraph.com', 'https://logos.hunter.io/sourcegraph.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Tabnine', 'https://www.tabnine.com', 'https://logos.hunter.io/tabnine.com', 'Developer Tools', 'Tel Aviv, Israel'),
    (NULL, 'Cursor', 'https://www.cursor.com', 'https://logos.hunter.io/cursor.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Windsurf', 'https://www.codeium.com', 'https://logos.hunter.io/codeium.com', 'Developer Tools', 'Mountain View, CA'),
    (NULL, 'Sentry', 'https://www.sentry.io', 'https://logos.hunter.io/sentry.io', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Bugsnag', 'https://www.bugsnag.com', 'https://logos.hunter.io/bugsnag.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Rollbar', 'https://www.rollbar.com', 'https://logos.hunter.io/rollbar.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Honeycomb', 'https://www.honeycomb.io', 'https://logos.hunter.io/honeycomb.io', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Lightstep', 'https://www.lightstep.com', 'https://logos.hunter.io/lightstep.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Chronosphere', 'https://www.chronosphere.io', 'https://logos.hunter.io/chronosphere.io', 'Developer Tools', 'New York, NY'),
    (NULL, 'VictorOps', 'https://www.victorops.com', 'https://logos.hunter.io/victorops.com', 'Developer Tools', 'Boulder, CO'),
    (NULL, 'Opsgenie', 'https://www.opsgenie.com', 'https://logos.hunter.io/opsgenie.com', 'Developer Tools', 'Boston, MA'),
    (NULL, 'Incident.io', 'https://www.incident.io', 'https://logos.hunter.io/incident.io', 'Developer Tools', 'London, UK'),
    (NULL, 'Rootly', 'https://www.rootly.com', 'https://logos.hunter.io/rootly.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'FireHydrant', 'https://www.firehydrant.com', 'https://logos.hunter.io/firehydrant.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'Blameless', 'https://www.blameless.com', 'https://logos.hunter.io/blameless.com', 'Developer Tools', 'San Mateo, CA'),
    (NULL, 'Kong', 'https://www.konghq.com', 'https://logos.hunter.io/konghq.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Tyk', 'https://www.tyk.io', 'https://logos.hunter.io/tyk.io', 'Developer Tools', 'London, UK'),
    (NULL, 'Apigee', 'https://www.cloud.google.com', 'https://logos.hunter.io/cloud.google.com', 'Developer Tools', 'Mountain View, CA'),
    (NULL, 'MuleSoft', 'https://www.mulesoft.com', 'https://logos.hunter.io/mulesoft.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Boomi', 'https://www.boomi.com', 'https://logos.hunter.io/boomi.com', 'Developer Tools', 'Chesterbrook, PA'),
    (NULL, 'Workato', 'https://www.workato.com', 'https://logos.hunter.io/workato.com', 'Developer Tools', 'Mountain View, CA'),
    (NULL, 'Tray.io', 'https://www.tray.io', 'https://logos.hunter.io/tray.io', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Zapier', 'https://www.zapier.com', 'https://logos.hunter.io/zapier.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Make', 'https://www.make.com', 'https://logos.hunter.io/make.com', 'Developer Tools', 'Prague, Czech Republic'),
    (NULL, 'n8n', 'https://www.n8n.io', 'https://logos.hunter.io/n8n.io', 'Developer Tools', 'Berlin, Germany'),
    (NULL, 'Temporal', 'https://www.temporal.io', 'https://logos.hunter.io/temporal.io', 'Developer Tools', 'Bellevue, WA'),
    (NULL, 'Camunda', 'https://www.camunda.com', 'https://logos.hunter.io/camunda.com', 'Developer Tools', 'Berlin, Germany'),
    (NULL, 'Airflow', 'https://www.airflow.apache.org', 'https://logos.hunter.io/airflow.apache.org', 'Developer Tools', 'Wilmington, DE'),
    (NULL, 'Prefect', 'https://www.prefect.io', 'https://logos.hunter.io/prefect.io', 'Developer Tools', 'Washington, DC'),
    (NULL, 'Dagster', 'https://www.dagster.io', 'https://logos.hunter.io/dagster.io', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'dbt Labs', 'https://www.getdbt.com', 'https://logos.hunter.io/getdbt.com', 'Developer Tools', 'Philadelphia, PA'),
    (NULL, 'Fivetran', 'https://www.fivetran.com', 'https://logos.hunter.io/fivetran.com', 'Developer Tools', 'Oakland, CA'),
    (NULL, 'Airbyte', 'https://www.airbyte.com', 'https://logos.hunter.io/airbyte.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Stitch', 'https://www.stitchdata.com', 'https://logos.hunter.io/stitchdata.com', 'Developer Tools', 'Philadelphia, PA'),
    (NULL, 'Matillion', 'https://www.matillion.com', 'https://logos.hunter.io/matillion.com', 'Developer Tools', 'Manchester, UK'),
    (NULL, 'Talend', 'https://www.talend.com', 'https://logos.hunter.io/talend.com', 'Developer Tools', 'Redwood City, CA'),
    (NULL, 'Informatica', 'https://www.informatica.com', 'https://logos.hunter.io/informatica.com', 'Developer Tools', 'Redwood City, CA'),
    (NULL, 'Collibra', 'https://www.collibra.com', 'https://logos.hunter.io/collibra.com', 'Developer Tools', 'Brussels, Belgium'),
    (NULL, 'Alation', 'https://www.alation.com', 'https://logos.hunter.io/alation.com', 'Developer Tools', 'Redwood City, CA'),
    (NULL, 'Monte Carlo', 'https://www.montecarlodata.com', 'https://logos.hunter.io/montecarlodata.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Bigeye', 'https://www.bigeye.com', 'https://logos.hunter.io/bigeye.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Great Expectations', 'https://www.greatexpectations.io', 'https://logos.hunter.io/greatexpectations.io', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Looker', 'https://www.looker.com', 'https://logos.hunter.io/looker.com', 'Developer Tools', 'Santa Cruz, CA'),
    (NULL, 'Tableau', 'https://www.tableau.com', 'https://logos.hunter.io/tableau.com', 'Developer Tools', 'Seattle, WA'),
    (NULL, 'Power BI', 'https://www.powerbi.microsoft.com', 'https://logos.hunter.io/powerbi.microsoft.com', 'Developer Tools', 'Redmond, WA'),
    (NULL, 'Mode', 'https://www.mode.com', 'https://logos.hunter.io/mode.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Hex', 'https://www.hex.tech', 'https://logos.hunter.io/hex.tech', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Observable', 'https://www.observablehq.com', 'https://logos.hunter.io/observablehq.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Sigma Computing', 'https://www.sigmacomputing.com', 'https://logos.hunter.io/sigmacomputing.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'ThoughtSpot', 'https://www.thoughtspot.com', 'https://logos.hunter.io/thoughtspot.com', 'Developer Tools', 'Mountain View, CA'),
    (NULL, 'Domo', 'https://www.domo.com', 'https://logos.hunter.io/domo.com', 'Developer Tools', 'American Fork, UT'),
    (NULL, 'Qlik', 'https://www.qlik.com', 'https://logos.hunter.io/qlik.com', 'Developer Tools', 'King of Prussia, PA'),
    (NULL, 'Sisense', 'https://www.sisense.com', 'https://logos.hunter.io/sisense.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'Metabase', 'https://www.metabase.com', 'https://logos.hunter.io/metabase.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Preset', 'https://www.preset.io', 'https://logos.hunter.io/preset.io', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Apache Superset', 'https://www.superset.apache.org', 'https://logos.hunter.io/superset.apache.org', 'Developer Tools', 'Wilmington, DE'),
    (NULL, 'Redash', 'https://www.redash.io', 'https://logos.hunter.io/redash.io', 'Developer Tools', 'Tel Aviv, Israel'),
    (NULL, 'Streamlit', 'https://www.streamlit.io', 'https://logos.hunter.io/streamlit.io', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Retool', 'https://www.retool.com', 'https://logos.hunter.io/retool.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Appsmith', 'https://www.appsmith.com', 'https://logos.hunter.io/appsmith.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Budibase', 'https://www.budibase.com', 'https://logos.hunter.io/budibase.com', 'Developer Tools', 'Belfast, UK'),
    (NULL, 'Tooljet', 'https://www.tooljet.com', 'https://logos.hunter.io/tooljet.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'OutSystems', 'https://www.outsystems.com', 'https://logos.hunter.io/outsystems.com', 'Developer Tools', 'Boston, MA'),
    (NULL, 'Mendix', 'https://www.mendix.com', 'https://logos.hunter.io/mendix.com', 'Developer Tools', 'Boston, MA'),
    (NULL, 'Appian', 'https://www.appian.com', 'https://logos.hunter.io/appian.com', 'Developer Tools', 'McLean, VA'),
    (NULL, 'Pega', 'https://www.pega.com', 'https://logos.hunter.io/pega.com', 'Developer Tools', 'Cambridge, MA'),
    (NULL, 'ServiceTitan', 'https://www.servicetitan.com', 'https://logos.hunter.io/servicetitan.com', 'SaaS', 'Glendale, CA'),
    (NULL, 'Procore', 'https://www.procore.com', 'https://logos.hunter.io/procore.com', 'SaaS', 'Carpinteria, CA'),
    (NULL, 'Autodesk', 'https://www.autodesk.com', 'https://logos.hunter.io/autodesk.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Bentley Systems', 'https://www.bentley.com', 'https://logos.hunter.io/bentley.com', 'SaaS', 'Exton, PA'),
    (NULL, 'Trimble', 'https://www.trimble.com', 'https://logos.hunter.io/trimble.com', 'SaaS', 'Westminster, CO'),
    (NULL, 'Anaplan', 'https://www.anaplan.com', 'https://logos.hunter.io/anaplan.com', 'SaaS', 'Miami, FL'),
    (NULL, 'Coupa', 'https://www.coupa.com', 'https://logos.hunter.io/coupa.com', 'SaaS', 'San Mateo, CA'),
    (NULL, 'Zuora', 'https://www.zuora.com', 'https://logos.hunter.io/zuora.com', 'SaaS', 'Redwood City, CA'),
    (NULL, 'Chargebee', 'https://www.chargebee.com', 'https://logos.hunter.io/chargebee.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Recurly', 'https://www.recurly.com', 'https://logos.hunter.io/recurly.com', 'SaaS', 'Boulder, CO'),
    (NULL, 'Maxio', 'https://www.maxio.com', 'https://logos.hunter.io/maxio.com', 'SaaS', 'Atlanta, GA'),
    (NULL, 'Bill.com', 'https://www.bill.com', 'https://logos.hunter.io/bill.com', 'Fintech', 'San Jose, CA'),
    (NULL, 'Tipalti', 'https://www.tipalti.com', 'https://logos.hunter.io/tipalti.com', 'Fintech', 'San Mateo, CA'),
    (NULL, 'AvidXchange', 'https://www.avidxchange.com', 'https://logos.hunter.io/avidxchange.com', 'Fintech', 'Charlotte, NC'),
    (NULL, 'Gusto', 'https://www.gusto.com', 'https://logos.hunter.io/gusto.com', 'Fintech', 'San Francisco, CA'),
    (NULL, 'Rippling', 'https://www.rippling.com', 'https://logos.hunter.io/rippling.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Deel', 'https://www.deel.com', 'https://logos.hunter.io/deel.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Remote', 'https://www.remote.com', 'https://logos.hunter.io/remote.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Oyster', 'https://www.oysterhr.com', 'https://logos.hunter.io/oysterhr.com', 'SaaS', 'Remote, US'),
    (NULL, 'Papaya Global', 'https://www.papayaglobal.com', 'https://logos.hunter.io/papayaglobal.com', 'SaaS', 'New York, NY'),
    (NULL, 'Lattice', 'https://www.lattice.com', 'https://logos.hunter.io/lattice.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Culture Amp', 'https://www.cultureamp.com', 'https://logos.hunter.io/cultureamp.com', 'SaaS', 'Melbourne, Australia'),
    (NULL, '15Five', 'https://www.15five.com', 'https://logos.hunter.io/15five.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'BambooHR', 'https://www.bamboohr.com', 'https://logos.hunter.io/bamboohr.com', 'SaaS', 'Lindon, UT'),
    (NULL, 'Greenhouse', 'https://www.greenhouse.io', 'https://logos.hunter.io/greenhouse.io', 'SaaS', 'New York, NY'),
    (NULL, 'Lever', 'https://www.lever.co', 'https://logos.hunter.io/lever.co', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Ashby', 'https://www.ashbyhq.com', 'https://logos.hunter.io/ashbyhq.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Gem', 'https://www.gem.com', 'https://logos.hunter.io/gem.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Eightfold AI', 'https://www.eightfold.ai', 'https://logos.hunter.io/eightfold.ai', 'AI/ML', 'Santa Clara, CA'),
    (NULL, 'Phenom', 'https://www.phenom.com', 'https://logos.hunter.io/phenom.com', 'SaaS', 'Ambler, PA'),
    (NULL, 'iCIMS', 'https://www.icims.com', 'https://logos.hunter.io/icims.com', 'SaaS', 'Holmdel, NJ'),
    (NULL, 'Workable', 'https://www.workable.com', 'https://logos.hunter.io/workable.com', 'SaaS', 'Boston, MA'),
    (NULL, 'SmartRecruiters', 'https://www.smartrecruiters.com', 'https://logos.hunter.io/smartrecruiters.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Beamery', 'https://www.beamery.com', 'https://logos.hunter.io/beamery.com', 'SaaS', 'London, UK'),
    (NULL, 'Paradox', 'https://www.paradox.ai', 'https://logos.hunter.io/paradox.ai', 'AI/ML', 'Scottsdale, AZ'),
    (NULL, 'HireVue', 'https://www.hirevue.com', 'https://logos.hunter.io/hirevue.com', 'SaaS', 'South Jordan, UT'),
    (NULL, 'Checkr', 'https://www.checkr.com', 'https://logos.hunter.io/checkr.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Vanta', 'https://www.vanta.com', 'https://logos.hunter.io/vanta.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Drata', 'https://www.drata.com', 'https://logos.hunter.io/drata.com', 'SaaS', 'San Diego, CA'),
    (NULL, 'Secureframe', 'https://www.secureframe.com', 'https://logos.hunter.io/secureframe.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Sprinto', 'https://www.sprinto.com', 'https://logos.hunter.io/sprinto.com', 'SaaS', 'San Francisco, CA'),
    (NULL, 'Anecdotes', 'https://www.anecdotes.ai', 'https://logos.hunter.io/anecdotes.ai', 'SaaS', 'Tel Aviv, Israel'),
    (NULL, 'Wiz', 'https://www.wiz.io', 'https://logos.hunter.io/wiz.io', 'Enterprise', 'New York, NY'),
    (NULL, 'Lacework', 'https://www.lacework.com', 'https://logos.hunter.io/lacework.com', 'Enterprise', 'Mountain View, CA'),
    (NULL, 'Orca Security', 'https://www.orca.security', 'https://logos.hunter.io/orca.security', 'Enterprise', 'Portland, OR'),
    (NULL, 'Aqua Security', 'https://www.aquasec.com', 'https://logos.hunter.io/aquasec.com', 'Enterprise', 'Ramat Gan, Israel'),
    (NULL, 'Sysdig', 'https://www.sysdig.com', 'https://logos.hunter.io/sysdig.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'Tailscale', 'https://www.tailscale.com', 'https://logos.hunter.io/tailscale.com', 'Developer Tools', 'Toronto, Canada'),
    (NULL, 'Twingate', 'https://www.twingate.com', 'https://logos.hunter.io/twingate.com', 'Developer Tools', 'Toronto, Canada'),
    (NULL, 'ZeroTier', 'https://www.zerotier.com', 'https://logos.hunter.io/zerotier.com', 'Developer Tools', 'Irvine, CA'),
    (NULL, 'WireGuard', 'https://www.wireguard.com', 'https://logos.hunter.io/wireguard.com', 'Developer Tools', 'Remote, US'),
    (NULL, 'Netskope', 'https://www.netskope.com', 'https://logos.hunter.io/netskope.com', 'Enterprise', 'Santa Clara, CA'),
    (NULL, 'Rubrik', 'https://www.rubrik.com', 'https://logos.hunter.io/rubrik.com', 'Enterprise', 'Palo Alto, CA'),
    (NULL, 'Cohesity', 'https://www.cohesity.com', 'https://logos.hunter.io/cohesity.com', 'Enterprise', 'San Jose, CA'),
    (NULL, 'Veeam', 'https://www.veeam.com', 'https://logos.hunter.io/veeam.com', 'Enterprise', 'Alpharetta, GA'),
    (NULL, 'Commvault', 'https://www.commvault.com', 'https://logos.hunter.io/commvault.com', 'Enterprise', 'Tinton Falls, NJ'),
    (NULL, 'Pure Storage', 'https://www.purestorage.com', 'https://logos.hunter.io/purestorage.com', 'Enterprise', 'Santa Clara, CA'),
    (NULL, 'NetApp', 'https://www.netapp.com', 'https://logos.hunter.io/netapp.com', 'Enterprise', 'San Jose, CA'),
    (NULL, 'Western Digital', 'https://www.westerndigital.com', 'https://logos.hunter.io/westerndigital.com', 'Enterprise', 'San Jose, CA'),
    (NULL, 'Seagate', 'https://www.seagate.com', 'https://logos.hunter.io/seagate.com', 'Enterprise', 'Fremont, CA'),
    (NULL, 'Cloudinary', 'https://www.cloudinary.com', 'https://logos.hunter.io/cloudinary.com', 'Developer Tools', 'Santa Clara, CA'),
    (NULL, 'Imgix', 'https://www.imgix.com', 'https://logos.hunter.io/imgix.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Uploadcare', 'https://www.uploadcare.com', 'https://logos.hunter.io/uploadcare.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Mux', 'https://www.mux.com', 'https://logos.hunter.io/mux.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Bunny.net', 'https://www.bunny.net', 'https://logos.hunter.io/bunny.net', 'Developer Tools', 'Ljubljana, Slovenia'),
    (NULL, 'Algolia', 'https://www.algolia.com', 'https://logos.hunter.io/algolia.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Typesense', 'https://www.typesense.org', 'https://logos.hunter.io/typesense.org', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Meilisearch', 'https://www.meilisearch.com', 'https://logos.hunter.io/meilisearch.com', 'Developer Tools', 'Paris, France'),
    (NULL, 'OpenSearch', 'https://www.opensearch.org', 'https://logos.hunter.io/opensearch.org', 'Developer Tools', 'Palo Alto, CA'),
    (NULL, 'Solr', 'https://www.solr.apache.org', 'https://logos.hunter.io/solr.apache.org', 'Developer Tools', 'Wilmington, DE'),
    (NULL, 'Coveo', 'https://www.coveo.com', 'https://logos.hunter.io/coveo.com', 'Developer Tools', 'Quebec City, Canada'),
    (NULL, 'Yext', 'https://www.yext.com', 'https://logos.hunter.io/yext.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'Contentful', 'https://www.contentful.com', 'https://logos.hunter.io/contentful.com', 'Developer Tools', 'Berlin, Germany'),
    (NULL, 'Sanity', 'https://www.sanity.io', 'https://logos.hunter.io/sanity.io', 'Developer Tools', 'Oslo, Norway'),
    (NULL, 'Strapi', 'https://www.strapi.io', 'https://logos.hunter.io/strapi.io', 'Developer Tools', 'Paris, France'),
    (NULL, 'Prismic', 'https://www.prismic.io', 'https://logos.hunter.io/prismic.io', 'Developer Tools', 'Paris, France'),
    (NULL, 'Storyblok', 'https://www.storyblok.com', 'https://logos.hunter.io/storyblok.com', 'Developer Tools', 'Linz, Austria'),
    (NULL, 'Webflow', 'https://www.webflow.com', 'https://logos.hunter.io/webflow.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Framer', 'https://www.framer.com', 'https://logos.hunter.io/framer.com', 'Developer Tools', 'Amsterdam, Netherlands'),
    (NULL, 'Squarespace', 'https://www.squarespace.com', 'https://logos.hunter.io/squarespace.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'Wix', 'https://www.wix.com', 'https://logos.hunter.io/wix.com', 'Developer Tools', 'Tel Aviv, Israel'),
    (NULL, 'WordPress', 'https://www.wordpress.com', 'https://logos.hunter.io/wordpress.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Ghost', 'https://www.ghost.org', 'https://logos.hunter.io/ghost.org', 'Developer Tools', 'Remote, US'),
    (NULL, 'Substack', 'https://www.substack.com', 'https://logos.hunter.io/substack.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Medium', 'https://www.medium.com', 'https://logos.hunter.io/medium.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Hashnode', 'https://www.hashnode.com', 'https://logos.hunter.io/hashnode.com', 'Developer Tools', 'San Francisco, CA'),
    (NULL, 'Dev.to', 'https://www.dev.to', 'https://logos.hunter.io/dev.to', 'Developer Tools', 'Remote, US'),
    (NULL, 'Stack Overflow', 'https://www.stackoverflow.com', 'https://logos.hunter.io/stackoverflow.com', 'Developer Tools', 'New York, NY'),
    (NULL, 'Hacker News', 'https://www.ycombinator.com', 'https://logos.hunter.io/ycombinator.com', 'Developer Tools', 'Mountain View, CA'),
    (NULL, 'Techstars', 'https://www.techstars.com', 'https://logos.hunter.io/techstars.com', 'Startup', 'Boulder, CO'),
    (NULL, '500 Global', 'https://www.500.co', 'https://logos.hunter.io/500.co', 'Startup', 'San Francisco, CA'),
    (NULL, 'a16z', 'https://www.a16z.com', 'https://logos.hunter.io/a16z.com', 'Startup', 'Menlo Park, CA'),
    (NULL, 'Sequoia Capital', 'https://www.sequoiacap.com', 'https://logos.hunter.io/sequoiacap.com', 'Startup', 'Menlo Park, CA'),
    (NULL, 'Accel', 'https://www.accel.com', 'https://logos.hunter.io/accel.com', 'Startup', 'Palo Alto, CA'),
    (NULL, 'Benchmark', 'https://www.benchmark.com', 'https://logos.hunter.io/benchmark.com', 'Startup', 'San Francisco, CA'),
    (NULL, 'Greylock', 'https://www.greylock.com', 'https://logos.hunter.io/greylock.com', 'Startup', 'Menlo Park, CA'),
    (NULL, 'Lightspeed', 'https://www.lsvp.com', 'https://logos.hunter.io/lsvp.com', 'Startup', 'Menlo Park, CA'),
    (NULL, 'Index Ventures', 'https://www.indexventures.com', 'https://logos.hunter.io/indexventures.com', 'Startup', 'San Francisco, CA'),
    (NULL, 'Bessemer Venture Partners', 'https://www.bvp.com', 'https://logos.hunter.io/bvp.com', 'Startup', 'San Francisco, CA'),
    (NULL, 'General Catalyst', 'https://www.generalcatalyst.com', 'https://logos.hunter.io/generalcatalyst.com', 'Startup', 'San Francisco, CA'),
    (NULL, 'Insight Partners', 'https://www.insightpartners.com', 'https://logos.hunter.io/insightpartners.com', 'Startup', 'New York, NY'),
    (NULL, 'Tiger Global', 'https://www.tigerglobal.com', 'https://logos.hunter.io/tigerglobal.com', 'Startup', 'New York, NY'),
    (NULL, 'SoftBank Vision Fund', 'https://www.softbank.com', 'https://logos.hunter.io/softbank.com', 'Startup', 'Tokyo, Japan'),
    (NULL, 'Databricks Mosaic', 'https://www.mosaicml.com', 'https://logos.hunter.io/mosaicml.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Groq', 'https://www.groq.com', 'https://logos.hunter.io/groq.com', 'AI/ML', 'Mountain View, CA'),
    (NULL, 'Cerebras', 'https://www.cerebras.ai', 'https://logos.hunter.io/cerebras.ai', 'AI/ML', 'Sunnyvale, CA'),
    (NULL, 'SambaNova', 'https://www.sambanova.ai', 'https://logos.hunter.io/sambanova.ai', 'AI/ML', 'Palo Alto, CA'),
    (NULL, 'Graphcore', 'https://www.graphcore.ai', 'https://logos.hunter.io/graphcore.ai', 'AI/ML', 'Bristol, UK'),
    (NULL, 'Habana Labs', 'https://www.habana.ai', 'https://logos.hunter.io/habana.ai', 'AI/ML', 'Caesarea, Israel'),
    (NULL, 'Tenstorrent', 'https://www.tenstorrent.com', 'https://logos.hunter.io/tenstorrent.com', 'AI/ML', 'Toronto, Canada'),
    (NULL, 'Modular', 'https://www.modular.com', 'https://logos.hunter.io/modular.com', 'AI/ML', 'Palo Alto, CA'),
    (NULL, 'Anyscale', 'https://www.anyscale.com', 'https://logos.hunter.io/anyscale.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Ray', 'https://www.ray.io', 'https://logos.hunter.io/ray.io', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'H2O.ai', 'https://www.h2o.ai', 'https://logos.hunter.io/h2o.ai', 'AI/ML', 'Mountain View, CA'),
    (NULL, 'Dataiku', 'https://www.dataiku.com', 'https://logos.hunter.io/dataiku.com', 'AI/ML', 'New York, NY'),
    (NULL, 'Domino Data Lab', 'https://www.dominodatalab.com', 'https://logos.hunter.io/dominodatalab.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Saturn Cloud', 'https://www.saturncloud.io', 'https://logos.hunter.io/saturncloud.io', 'AI/ML', 'Austin, TX'),
    (NULL, 'Paperspace', 'https://www.paperspace.com', 'https://logos.hunter.io/paperspace.com', 'AI/ML', 'New York, NY'),
    (NULL, 'Lambda Labs', 'https://www.lambdalabs.com', 'https://logos.hunter.io/lambdalabs.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'CoreWeave', 'https://www.coreweave.com', 'https://logos.hunter.io/coreweave.com', 'AI/ML', 'Roseland, NJ'),
    (NULL, 'Together AI', 'https://www.together.ai', 'https://logos.hunter.io/together.ai', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Fireworks AI', 'https://www.fireworks.ai', 'https://logos.hunter.io/fireworks.ai', 'AI/ML', 'Redwood City, CA'),
    (NULL, 'Baseten', 'https://www.baseten.co', 'https://logos.hunter.io/baseten.co', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Modal', 'https://www.modal.com', 'https://logos.hunter.io/modal.com', 'AI/ML', 'New York, NY'),
    (NULL, 'Banana', 'https://www.banana.dev', 'https://logos.hunter.io/banana.dev', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Beam', 'https://www.beam.cloud', 'https://logos.hunter.io/beam.cloud', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'RunPod', 'https://www.runpod.io', 'https://logos.hunter.io/runpod.io', 'AI/ML', 'Austin, TX'),
    (NULL, 'Vast.ai', 'https://www.vast.ai', 'https://logos.hunter.io/vast.ai', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Labelbox', 'https://www.labelbox.com', 'https://logos.hunter.io/labelbox.com', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Snorkel AI', 'https://www.snorkel.ai', 'https://logos.hunter.io/snorkel.ai', 'AI/ML', 'Redwood City, CA'),
    (NULL, 'Surge AI', 'https://www.surgehq.ai', 'https://logos.hunter.io/surgehq.ai', 'AI/ML', 'San Francisco, CA'),
    (NULL, 'Turing', 'https://www.turing.com', 'https://logos.hunter.io/turing.com', 'AI/ML', 'Palo Alto, CA'),
    (NULL, 'Anduril', 'https://www.anduril.com', 'https://logos.hunter.io/anduril.com', 'Enterprise', 'Costa Mesa, CA'),
    (NULL, 'SpaceX', 'https://www.spacex.com', 'https://logos.hunter.io/spacex.com', 'Enterprise', 'Hawthorne, CA'),
    (NULL, 'Blue Origin', 'https://www.blueorigin.com', 'https://logos.hunter.io/blueorigin.com', 'Enterprise', 'Kent, WA'),
    (NULL, 'Rocket Lab', 'https://www.rocketlabusa.com', 'https://logos.hunter.io/rocketlabusa.com', 'Enterprise', 'Long Beach, CA'),
    (NULL, 'Planet Labs', 'https://www.planet.com', 'https://logos.hunter.io/planet.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'Maxar', 'https://www.maxar.com', 'https://logos.hunter.io/maxar.com', 'Enterprise', 'Westminster, CO'),
    (NULL, 'Waymo', 'https://www.waymo.com', 'https://logos.hunter.io/waymo.com', 'Enterprise', 'Mountain View, CA'),
    (NULL, 'Cruise', 'https://www.getcruise.com', 'https://logos.hunter.io/getcruise.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'Aurora', 'https://www.aurora.tech', 'https://logos.hunter.io/aurora.tech', 'Enterprise', 'Pittsburgh, PA'),
    (NULL, 'Nuro', 'https://www.nuro.ai', 'https://logos.hunter.io/nuro.ai', 'Enterprise', 'Mountain View, CA'),
    (NULL, 'Zoox', 'https://www.zoox.com', 'https://logos.hunter.io/zoox.com', 'Enterprise', 'Foster City, CA'),
    (NULL, 'Rivian', 'https://www.rivian.com', 'https://logos.hunter.io/rivian.com', 'Enterprise', 'Irvine, CA'),
    (NULL, 'Lucid Motors', 'https://www.lucidmotors.com', 'https://logos.hunter.io/lucidmotors.com', 'Enterprise', 'Newark, CA'),
    (NULL, 'NIO', 'https://www.nio.com', 'https://logos.hunter.io/nio.com', 'Enterprise', 'Shanghai, China'),
    (NULL, 'XPeng', 'https://www.xiaopeng.com', 'https://logos.hunter.io/xiaopeng.com', 'Enterprise', 'Guangzhou, China'),
    (NULL, 'BYD', 'https://www.byd.com', 'https://logos.hunter.io/byd.com', 'Enterprise', 'Shenzhen, China'),
    (NULL, 'Mobileye', 'https://www.mobileye.com', 'https://logos.hunter.io/mobileye.com', 'Enterprise', 'Jerusalem, Israel'),
    (NULL, 'Luminar', 'https://www.luminartech.com', 'https://logos.hunter.io/luminartech.com', 'Enterprise', 'Orlando, FL'),
    (NULL, 'Aeva', 'https://www.aeva.com', 'https://logos.hunter.io/aeva.com', 'Enterprise', 'Mountain View, CA'),
    (NULL, 'Ouster', 'https://www.ouster.com', 'https://logos.hunter.io/ouster.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'Velodyne', 'https://www.velodynelidar.com', 'https://logos.hunter.io/velodynelidar.com', 'Enterprise', 'San Jose, CA'),
    (NULL, 'Samsara', 'https://www.samsara.com', 'https://logos.hunter.io/samsara.com', 'Enterprise', 'San Francisco, CA'),
    (NULL, 'Verkada', 'https://www.verkada.com', 'https://logos.hunter.io/verkada.com', 'Enterprise', 'San Mateo, CA'),
    (NULL, 'Ring', 'https://www.ring.com', 'https://logos.hunter.io/ring.com', 'Consumer Tech', 'Santa Monica, CA'),
    (NULL, 'Nest', 'https://www.store.google.com', 'https://logos.hunter.io/store.google.com', 'Consumer Tech', 'Mountain View, CA'),
    (NULL, 'Arlo', 'https://www.arlo.com', 'https://logos.hunter.io/arlo.com', 'Consumer Tech', 'San Jose, CA'),
    (NULL, 'Ecobee', 'https://www.ecobee.com', 'https://logos.hunter.io/ecobee.com', 'Consumer Tech', 'Toronto, Canada'),
    (NULL, 'Sonos', 'https://www.sonos.com', 'https://logos.hunter.io/sonos.com', 'Consumer Tech', 'Santa Barbara, CA'),
    (NULL, 'Peloton', 'https://www.onepeloton.com', 'https://logos.hunter.io/onepeloton.com', 'Consumer Tech', 'New York, NY'),
    (NULL, 'Whoop', 'https://www.whoop.com', 'https://logos.hunter.io/whoop.com', 'Consumer Tech', 'Boston, MA'),
    (NULL, 'Oura', 'https://www.ouraring.com', 'https://logos.hunter.io/ouraring.com', 'Consumer Tech', 'Oulu, Finland'),
    (NULL, 'Fitbit', 'https://www.fitbit.com', 'https://logos.hunter.io/fitbit.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Garmin', 'https://www.garmin.com', 'https://logos.hunter.io/garmin.com', 'Consumer Tech', 'Olathe, KS'),
    (NULL, 'Strava', 'https://www.strava.com', 'https://logos.hunter.io/strava.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Calm', 'https://www.calm.com', 'https://logos.hunter.io/calm.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Headspace', 'https://www.headspace.com', 'https://logos.hunter.io/headspace.com', 'Consumer Tech', 'Santa Monica, CA'),
    (NULL, 'Noom', 'https://www.noom.com', 'https://logos.hunter.io/noom.com', 'Consumer Tech', 'New York, NY'),
    (NULL, 'MyFitnessPal', 'https://www.myfitnesspal.com', 'https://logos.hunter.io/myfitnesspal.com', 'Consumer Tech', 'Austin, TX'),
    (NULL, 'ClassPass', 'https://www.classpass.com', 'https://logos.hunter.io/classpass.com', 'Consumer Tech', 'New York, NY'),
    (NULL, 'Tonal', 'https://www.tonal.com', 'https://logos.hunter.io/tonal.com', 'Consumer Tech', 'San Francisco, CA'),
    (NULL, 'Mirror', 'https://www.mirror.co', 'https://logos.hunter.io/mirror.co', 'Consumer Tech', 'New York, NY'),
    (NULL, 'Roku', 'https://www.roku.com', 'https://logos.hunter.io/roku.com', 'Consumer Tech', 'San Jose, CA')
ON CONFLICT (company_name) WHERE company_user_id IS NULL DO NOTHING;
